---
- name: Ensure all users in group "sudo" can sudo without password
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%sudo\s+ALL='
    line: '%sudo ALL=(ALL) NOPASSWD: ALL'
    validate: '/usr/sbin/visudo -cf %s'
  become: true